### ISSUE TITLE
Info tooltips in seatmap

### ISSUE THREAD

**Issue by lizter** [dotKom/studlan#101]
It's a pain to click every seat to find out who sits there. I suggest making a tooltip on hover that displays the name of the person sitting there.

**Comment by larserikgk** [comment]
There should be a tooltip that displays the username of a chosen seat on hover. Works for me on current deployment with firefox 35. Would it be better to display the full name?

**Comment by melwil** [comment]
There is no hover tooltip in chrome, as far as I can tell. Also, a regular hover is way too slow for this, it needs to pop up near-instant if you are to check every seat.
